attention_dropout: 0.1
bs: 32
contrastive: true
contrastive_coeff: 0.1
has_additional_prompt: false
hidden_dropout: 0.1
lr: 2.0e-05
model_style: classification
num_workers: 8
output_attentions: true
pretrained_model: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext
weight_decay: 0.001
